### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Alexikon** [rstropek-teaching/pokelist-quiz-4bhif-Alexikon#1]
I do not know why, but the details do not get shown.

**Comment by Alexikon** [comment]
es kommt nicht in die showPokeDetails methode

**Comment by rstropek** [comment]
@Alexikon Your problem is that your `showPokeDetails` is not defined as a global method. That is positiv! It is good not to publish methods globally. However, you cannot call a hidden method in `onclick`. You need a different method for that.

I created a [commit](https://github.com/rstropek-teaching/pokelist-quiz-4bhif-Alexikon/commit/6cd14cadb46e2d2a8f0e06f9397ebd909ac14ce2) for your repository that fixes the problem. Note how I use a *HTML5 data attribute* to store the URL for the Pokemon details. In the jQuery `click` handler, I access this data attribute.

I hope my contribution is useful. Don't hesitate to contact me in case of questions.

Greetings,
Rainer Stropek.
